import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[3]
manifest=json.loads((ROOT/'raw/practitioner-practices-development/extraction/manifest.json').read_text(encoding='utf-8'))
sources={s['id']:s for s in manifest['sources']}
# Bibliography recorded in screening/shortlist.md, final provenance note.
sources[255]['date']='2026-07-20'
sources[255]['url']='https://hbr.org/2026/07/design-ai-systems-that-actually-strengthen-human-reasoning'
reviews={}
cards=[]
def review(id, author, decision, locators, basis, reported, proposed, limits, note, merge=None):
    s=sources[id]
    reviews[id]=dict(id=id,author=author,group_index=s['group_index'],decision=decision,locators=locators.split('|'),basis=basis,reported_outcomes=[reported],proposed_outcomes=[proposed],limits=limits.split('|'),review_note=note,merge=merge)
def card(id,stem,title,use,steps,notice):
    cards.append(dict(id=id,stem=stem,title=title,use=use,steps=steps.split('|'),notice=notice))

review(512,"Laura O'Driscoll, with Sam Illingworth",'retain','L28–36, Step-by-step|L56–80, A moment from Laura|L100–108, What to do with it','First-person repeated-use account and proposed prompt','O’Driscoll describes questions that paused her thinking and says some positions changed; no independent assessment.','Examine assumptions and the reasons for holding a belief.','Questions can embed a false premise about upbringing, motives or emotion.|Felt insight is not evidence that a revised belief is true.','Retain the human answers and tension sentence; do not frame the model as an authority on the origin of beliefs.')
card(512,'answer-questions-about-your-belief','Answer questions about a belief you hold','You want to examine a claim you keep defending, without asking AI to decide what you should believe.','State the belief in your own words. Keep identifying or sensitive material out.|Ask AI for clarifying questions about assumptions and trade-offs; answer them yourself.|Inspect a question before answering. [Inference] Reject a premise that does not fit your experience instead of explaining why it must be true.|Write a sentence capturing the tension you still hold. [Inference] Identify factual claims requiring evidence outside the conversation before changing or publishing your view.','[Inference] Keep the initial and final belief sentences and the reason for any change. A shift in certainty alone is not improvement.')
review(387,'Sabrina Ramonov','merge','L61–109, context and sparring prompts|L115–156, persistence setup','First-person business anecdote plus illustrative prompt','Reports avoiding a proposed marketing spend; the claim that it would have failed is counterfactual and unverified.','Surface business risks and overlooked questions.','Claims of becoming 10 times smarter or saving hours are unsupported.|Paid-plan requirements and product memory claims are dated, not prerequisites for the routine.|A sparring prompt can invent objections or flatter the user through apparent toughness.','Merge as a business variant of answering questions about one’s belief. Use supplied task facts, not indiscriminate personal or client disclosure.',512)
review(270,'Ruben Hassid','merge','L38–82, answer and challenge assumptions|L92–118, Perspective Transition','Worked business-plan example in incomplete available article','Author reports questioning invented pricing and preferring a later angle.','Consider contrasting views and challenge unsupported assumptions.','Available text ends at the section 3 heading; missing conclusion remains an access limitation.|Simulated experts are not independent witnesses; supplied quotes and sources require checking.|Being satisfied with an answer is not verification.','Merge the demonstrated challenge to invented assumptions; exclude the claim that both simulated expert views are valid.',512)
review(294,'Ruben Hassid','counterexample','L93–105, example|L149–171, default prompt|L268–272, human-decision recipe','Prescriptive newsletter with inconsistent procedures','No comparative evaluation of the proposed sequence.','Separate options, choice and drafting.','Main prompt instructs AI to recommend one option and draft immediately, despite text saying the person decides.|Usage frequencies and satisfaction do not establish judgment improvement.','Changed from selected practice: keep as a counterexample showing why a claimed human decision step must exist in the actual procedure.')
review(352,'Sabrina Ramonov','counterexample','L55–105, three prompts|L117–125, warning','Proposed commercial prompt chain','No business results reported for this chain.','Select an idea to test using existing skills and recoverable downside.','AI memory may omit or invent personal capabilities.|Resemblance to a generated quitter profile is not evidence to reject a business.|An AI-selected winner and forced certainty can displace the person’s judgment.','Changed from supportive variant: retain as a counterexample to inferring identity and choosing a consequential plan from model-generated personality claims.')
review(413,'Ting Wang (Tzu-Ting), with Sam Illingworth','retain','L24, attribution|L30–40, return-path prompt|L44–58, account and reflection','First-person career account plus proposed AI inquiry','Wang reports that naming the cost of returning reduced felt pressure during a career choice; the account does not isolate AI’s contribution.','Make practical reversibility and constraints explicit.','Visa, tax, pension and employment facts need authoritative checking; none is established by the prompt.|AI must not reclassify a structural constraint as merely emotional.|A return route can change after the decision.','Retain as an inquiry checklist, not career, tax or legal advice.')
card(413,'map-a-return-path','Map a return path before choosing','A career or work choice feels irreversible and you need to distinguish actual constraints from assumptions.','Describe the choice, timeline and non-sensitive constraints.|Ask one question at a time about what returning would require in time, money and effort. Answer from your circumstances.|Map a possible route back and mark what is known, uncertain or assumed.|[Inference] Verify consequential external rules and costs with the relevant authoritative source or adviser. Decide yourself whether the remaining downside is acceptable.','[Inference] Notice whether the return path became more specific, rather than merely more reassuring. Keep unresolved constraints visible.')
review(439,'Raghav Mehra, reframed by Sam Illingworth','retain','L20–24, attribution and rationale|L30–58, three-stage prompt|L78–94, newsletter example','Proposed framework with first-person before/after demonstration','Mehra describes a more actionable newsletter answer after narrowing the question; no outcome comparison.','Tie research to a decision and signals that could change it.','Narrowing too early can exclude disconfirming evidence.|Weighted insights are generated priorities, not measured weights.|A specific answer can still be false.','Retain decision and change-signals framing. Credit the named guest despite an embedded publication card naming a different author.')
card(439,'define-the-decision-before-research','Define the decision before asking AI to research','You keep collecting broad briefings but cannot say what they should change.','State the decision the research must inform.|Ask AI to help clarify the smallest useful question, three to five signals that would change your decision, and what can be excluded. Answer these questions yourself.|Confirm the focused question and signals before research begins.|Ask for a short set of insights, their practical implications and uncertainties; then identify what is still missing for your context.|[Inference] Check decisive evidence against its sources and reopen the scope if the exclusions removed a serious alternative.','[Inference] Record which piece of evidence changed a decision, or state that none did. Brevity and apparent actionability are separate from accuracy.')
review(515,'Alena Gorb, with Sam Illingworth','merge','L40–58, inquiry prompt|L62–88, Sonnet demonstration|L104–110, broad claims','First-person demonstration and proposed constraint exercise','Gorb reports recognizing tension between a newsletter ambition and expectations of success.','Move from generating options to examining reasons for commitment.','Discomfort is not truth and may indicate an unsuitable question.|The model’s claim about needing external validation is an interpretation, not a diagnosis.|A fixed six-month refusal to pivot is not established good practice; the article’s universal cowardice and cognition claims are excluded.','Merge as a commitment-question variant; retain the useful request to define success concretely and reject psychological certainty.',512)
review(578,'Brian Tolkin, interviewed by Lenny Rachitsky','merge','00:40:00–00:47:04; L357–394','Professional retrospective and practical heuristic','Describes experimentation limits at Opendoor and use of customers, peers and post-launch feedback; no evaluation of this checklist.','Match evidence-seeking to uncertainty and consequences.','Higher personal conviction or peer agreement does not establish correctness.|The transcript conflates statistical power and confidence; do not copy numerical testing advice.','Merge into evidence-strength review; the post-release feedback loop is a useful addition.',663)
review(663,'Itamar Gilad, interviewed by Lenny Rachitsky','retain','00:37:04–00:45:50; L296–345','Practitioner tool explanation and reported field use','Gilad reports teams use the confidence meter to challenge poorly supported investment; no controlled comparison.','Distinguish enthusiasm, opinion, data and tests when judging a proposal.','Confidence-meter numbers are a heuristic, not calibrated probabilities.|Large datasets and tests can still be biased or poorly designed.|Some low-consequence changes do not justify additional testing.','Retain evidence categories and proportionate next steps; omit pseudo-precise numeric thresholds.')
card(663,'match-confidence-to-evidence','Match confidence to the evidence you have','A proposal looks persuasive and the team must decide how much to invest.','List the evidence behind your estimate: conviction, thematic fit, colleague review, customer observations, broader data or an actual test.|Separate your enthusiasm from the strength and relevance of that evidence.|Choose the next affordable check in proportion to the stakes. A low-risk change may not need more research.|If you proceed with uncertainty, define a feedback route that could reveal a wrong assumption, following Tolkin’s variant.|[Inference] Treat an AI recommendation as a proposal until you inspect the evidence it uses; fluent prose adds no independent evidence.','[Inference] Ask what observation would lower confidence. Do not turn the practitioner’s confidence scale into a probability of success.')
review(710,'Kevin Yien, interviewed by Lenny Rachitsky','retain','00:35:13–00:42:42; L366–412|00:44:07–00:45:02; L423–430','First-person repeated practice with one retrospective example','Reports learning from decision records; his Shopify example matched direction but missed some underlying reasons.','Create repeated opportunities to compare prior reasoning with later outcomes.','A market prediction log is not a replacement for doing the work; Yien states this explicitly.|Outcomes depend on luck and unavailable facts, not only reasoning quality.|AI-generated predictions would exercise a different skill from making one yourself.','Retain the dated record and scheduled revisit; AI adaptation is curator inference.')
card(710,'keep-a-decision-and-outcome-log','Keep a decision and outcome log','You want to learn from decisions without rewriting your memory after the result.','Write a decision or prediction, your rationale and the information available at the time. It can concern your work or a public product decision.|Start small: Yien suggests one brief entry each week.|Set a calendar date to revisit the outcome.|Compare the original reasoning with what happened and, where available, the actual reasons behind another team’s choice.|[Inference] If AI contributes, preserve your initial judgment separately and label what changed after its input. Do not let a retrospective AI summary replace the original record.','[Inference] Notice wrong reasons behind right predictions as well as wrong outcomes. Count uncertainty and missing information, not only wins.')

review(286,'Ruben Hassid','retain','L515–535, Archive-to-Argument|L419–427, advising versus acting','Proposed workflow with brief first-person endorsement','Author says the generated draft sounded like him; screenshots and linked demonstrations were not independently evaluated.','Find competing arguments in existing material and keep the choice with the writer.','Three generated options can all share the same framing.|Choosing an argument does not establish that generated prose is personally authored.|Product, pricing and security claims elsewhere are not adopted; selecting a paid plan does not itself settle data permissions.','Extract only the archive-to-argument procedure from the full available guide, with an explicit human choice before drafting.')
card(286,'choose-an-argument-before-drafting','Choose an argument before drafting from your archive','You have notes or research but no settled argument, and want to explore what they could support.','Supply selected material, audience, publication context and the intended reader takeaway.|Ask AI to identify tensions, surprises and open questions; have it ask what you believe, witnessed and are willing to say publicly.|Request three different arguments, each with what it emphasizes and sacrifices. Stop before drafting.|Choose, reject or replace the proposed arguments yourself.|If you authorize a draft, require unsupported claims to remain visible as gaps. [Inference] Check those flags against the archive yourself and preserve which language was generated.','[Inference] Notice whether you can explain why you rejected the other routes and whether the chosen argument is actually supported by your material.')
review(306,'Ruben Hassid','retain','L144–254, taste interview|L256–420, profile specification|L472–476, updates|L550–556, AI authorship disclosure','First-person process account; article disclosed as AI-generated','Reports making a preference file after an interview and finding its output closer to his style; no independent voice or thinking test.','Make writing preferences explicit enough to use and revise.','A text profile is not a person, identity or complete thinking process.|The demand for exactly 100 questions and pressure not to accept uncertainty are not validated requirements.|Removing hedging as a style rule must not erase evidential uncertainty.','Retain an example-based preference interview; reject the central claim that reproducing style duplicates a person.')
card(306,'articulate-your-writing-preferences','Articulate your writing preferences through examples','AI edits keep sounding generic and you have trouble explaining what you want.','Ask AI to interview you one question at a time about sentence choices, structure, examples you like, and things you reject.|Answer with actual examples, rather than labels such as conversational or clear.|When answers conflict, inspect the examples and decide whether the preference depends on context.|Have AI compile the questions and your answers, separating strong boundaries from flexible preferences. [Inference] Correct the record yourself and retain unknowns rather than forcing certainty.|Use and revise the profile as your preferences evolve; it remains a guide to stated preferences, not a substitute for your judgment.','[Inference] Notice whether you can now explain an editing choice more precisely without the profile. A convincing imitation is a different outcome.')
review(409,'Susan Gordon Byron, with Sam Illingworth','retain','L16, attribution|L36–52, sensory prompt|L72–82, Lumo account','Proposed exercise and first-person exploration','Byron reports questioning Lumo about sensory and mathematical transformations; no accessibility evaluation.','Notice whether a tool respects a stated sensory association rather than correcting it as a factual error.','The model has no demonstrated felt association; its explanation is generated language.|One response cannot diagnose a neurotypical system or represent all neurodiverse users.|Respecting a creative association differs from agreeing with a harmful factual belief.','Retain as an interaction and creative-expression exercise, not a test of consciousness or clinical accessibility.')
card(409,'keep-your-sensory-association-in-the-work','Keep your sensory association in the work','A creative tool turns a personal sensory association into a factual correction.','Choose a harmless sensory question, such as a colour associated with a day.|Ask briefly for a response without correction. If needed, clarify that you are exploring an association, not a factual claim.|Compare the generated association with your own; you need not adopt its answer.|Supply your own association and ask for a small scene that preserves it.|[Inference] Judge the scene against the experience you intended to express, rather than treating the model’s explanation as perception.','[Inference] Identify one place where the system preserved or flattened your association. Keep subjective expression distinct from factual verification.')
review(425,'Steve Peha, with Sam Illingworth','retain','L18–22, attribution|L30–40, classroom procedure|L60–106, personal example','Proposed classroom exercise with adult first-person demonstration','Peha reports personal reflection after a fictional-character prompt; no results from students using this exact classroom protocol.','Use fiction to prompt independent reflective writing before group discussion.','A generated character voice is an interpretation, not the original work or the author’s intention.|Private reflections need not be disclosed to the tool or classmates.|Five minutes of writing does not establish long-term inquiry or learning gains.','Retain the order: character prompt, independent student writing, then discussion. Do not imply the AI classroom routine itself has field evaluation.')
card(425,'use-fictional-questions-for-your-own-reflection','Use fictional questions for your own reflection','You have read a work and want to connect its questions to your own experience.','Choose a character and an idea from the work. Ask AI for one short paragraph in that character’s voice and three questions for you.|[Inference] Treat the response as a new interpretation and check any claims about the work against the text.|Write your own responses privately for five minutes, as the source suggests; do not ask AI to answer for you.|For a class, discuss after the individual writing. [Inference] Offer a fictional or non-personal response option and let students keep private material private.','[Inference] Notice which question led you to something you could support from the text or your own experience. Emotional resonance does not authenticate an interpretation.')
review(430,'Tom Evans, with Sam Illingworth','defer','L28–42, three-part prompt|L62–76, reported meditation interaction|L86–104, reflection guidance','First-person contemplative account and speculative interaction design','Evans reports clearer description of sensations and a calmer conversational rhythm.','Use questions to notice bodily experience and attention.','Reported tone and sensation changes are not validated meditation benefits.|Claims that AI recognized meditative depth from sparse words are interpretations.|The simulated-meditation framing encourages anthropomorphic assumptions and adds little to the already retained question-and-reflection routines.','Defer a standalone card. Preserve the useful boundary that the person reports sensations and judges distraction; revisit with a clearer non-speculative protocol.')
review(488,'Sam Illingworth','retain','L24–39, procedure|L43–56, demonstration|L60–70, use and limits','Playful proposed exercise with a short demonstration','Author found a poetic association in a deliberately wrong answer; no creativity outcome measure.','Generate unfamiliar associations for creative work.','Keep deliberate falsehood within clearly fictional, low-stakes play.|A compelling explanation is not evidence.|No demonstrated improvement in unaided creativity or collective diversity.','Retain one creative-constraint card with compression and uncertainty variants from 489 and 490; do not treat them as independent validation.')
card(488,'use-a-creative-constraint-and-respond','Use a creative constraint, then make something yourself','You are exploring a low-stakes creative question and want an unfamiliar starting point.','Ask AI for a deliberately wrong answer to a harmless question. Keep the fictional frame explicit.|Optionally ask for a fictional rationale or turn the answer into a short poem or headline.|Choose an association and use it to start your own story, image or thought.|Variants: 489 limits an answer to a few words, then a sentence or image; 490 requires an “I don’t know” response and explores what could be needed to know. Pick a variant deliberately.|[Inference] Keep factual research separate from this exercise and label invented material if it could be mistaken for information.','[Inference] Notice what you added or rejected, not just what the model produced. Forced uncertainty is role-play, not calibrated knowledge.')
review(489,'Sam Illingworth','merge','L24–40, length/media constraints|L48–70, demonstration and comparison','Proposed exercise and personal demonstration','Reports preferring a compressed answer about rest; no objective comparison.','Explore changes in meaning and tone through compression and media changes.','A shorter answer can erase important caveats.|Metaphorical depth is not truth or evidence.','Merge as a compression variant of creative constraints, keeping it separate from factual summarization.',488)
review(490,'Sam Illingworth','merge','L26–42, uncertainty instructions|L50–78, example and scope','Proposed uncertainty role-play with demonstration','Reports finding the forced non-answer more generous; no epistemic calibration measure.','Stay with an unresolved question and turn uncertainty into creative material.','The model is instructed to say it does not know, so the response says nothing about actual uncertainty.|Its claim about what science needs to know can itself be wrong.','Merge as a creative uncertainty variant, explicitly not an honesty or calibration technique.',488)
review(524,'Mia Kiraki, with Sam Illingworth','retain','L20, attribution|L38–52, missing chapter and timebox|L72–84, commentary','Proposed creative procedure; reflection rather than documented before/after project','No finished project comparison in this source; later reader reports appear in source 530.','Use generated material as a structural provocation for a bounded human experiment.','AI cannot discover the uniquely correct missing chapter or read the writer’s unspoken intention.|Generated autobiographical detail is not memory.|Thirty minutes is a suggested timebox, not an evaluated dose.','Retain testing one human-made change rather than automatically inserting the generated chapter.')
card(524,'test-one-creative-change','Test one creative change suggested by AI','A draft feels incomplete but you do not want to rewrite the whole project.','Supply a short section or outline and ask AI to propose a missing chapter connecting its ideas.|Read it as a possible direction, not a discovery of your hidden intention.|Choose one small change: move a paragraph, rewrite a passage in a consistent voice, or try another point of view.|Test that change for 30 minutes, the source’s suggested timebox, and decide whether it serves the piece.|A variant from Harry O’Hanley (530) uses imagined earlier-era constraints to suggest a change. [Inference] Verify historical claims before using them as evidence.','[Inference] Compare the changed passage with the saved original and explain what improved or was lost. You may reject the suggestion.')
review(530,'Harry O’Hanley, with Sam Illingworth','merge','L42–56, time-period prompt and test|L76–96, engineering example|L146–156, reader reports on 524','Proposed AI prompt plus separate professional anecdote','O’Hanley reports choosing an older structure design for engineering simplicity; the account does not say AI caused that decision. Reader comments report useful missing-chapter edits.','Challenge present assumptions through alternative constraints, then test a small change.','An era instruction does not prevent anachronistic information leakage.|The engineering example is not a test of the AI prompt.|Reader comments are second-hand anecdotal evidence, not independent evaluation.','Merge as a constrained-perspective variant of testing one creative change; avoid claiming the prompt proved engineering independence.',524)
review(558,'Arielle Jackson, interviewed by Lenny Rachitsky','retain','00:18:37–00:27:29; L204–277','Detailed professional naming process','Describes client naming work and trade-offs; no comparative trial.','Establish creative criteria, generate broadly, then choose with context.','Naming success depends on the product and execution as well as the name.|AI adaptation is not in the source.|Legal availability requires a separate competent check.','Retain the human naming procedure as a transferable baseline; optional AI additions are inference.')
card(558,'set-creative-criteria-before-generating','Set creative criteria before generating options','You need a name or creative direction and risk choosing whatever sounds impressive first.','Write the positioning and a brief: what is being named, desired associations, things to avoid, related names and audience constraints.|Bring together a small group with varied relevant perspectives. Generate word associations and themes before judging candidates.|Create a shortlist and compare it against the agreed criteria; Jackson uses red, yellow and green judgments.|Keep several contenders while checking practical constraints such as pronunciation, domain and legal availability.|[Inference] AI may add options after you define the brief. Retain people’s contributions and apply the same criteria to both.','[Inference] Notice whether criteria changed merely to favor the first attractive candidate. A long idea list is not a measure of creative judgment.')
review(605,'David Singleton, interviewed by Lenny Rachitsky','retain','01:25:30–01:27:17; L617–633','First-person family creative account','Reports making images with his nine-year-old daughter, who wrote the book prose; describes composing one cover from two images.','Use image support while leaving chosen writing work to the child.','Enjoyment and a finished book are not evidence of improved writing skill.|Product model-architecture statements are unverified and unnecessary.|Illustration is itself a creative skill; this allocation does not preserve all skills.','Retain a concrete division of creative work with an explicit learning-goal boundary.')
card(605,'let-the-child-write-the-story','Let the child write the story around supporting images','A child wants to make a story and the chosen activity is writing, while images can support it.','Develop a story idea together.|Generate or assemble supporting images together, following the child’s choices.|Let the child arrange the images and write the prose.|[Inference] Ask the child to explain an image or wording choice; do not have AI replace the part they wanted to practise.','[Inference] Notice the writing and choices the child actually did. If drawing is the learning goal, choose a different division of work.')
review(684,'Jessica Hische, interviewed by Lenny Rachitsky','retain','00:24:25–00:30:55; L162–190|01:01:49–01:05:50; L360–375','Professional creative account and a proposed noticing exercise','Reports selecting emotions from AI-generated lists for a children’s book and retaining production work she finds fulfilling; rejected one AI image experiment.','Articulate visual preferences; use a generated pool without surrendering selection or making.','Personal associations are not universal audience responses.|The noticing exercise and AI word-list workflow are separate practices, not a tested combined sequence.|No measured improvement in taste or originality.','Retain two distinct cards: observing one’s visual reactions and selecting from a generated creative pool.')
card(684,'name-your-own-visual-reactions','Name your own visual reactions','You can sense that a design feels right or wrong but struggle to explain why.','Look through examples such as fonts or logos and write your immediate reaction in plain words.|Collect examples with similar reactions.|Compare visible features such as spacing, weight, width or rounded edges and ask what might explain the grouping.|Use those observations to explain a creative choice. [Inference] If AI supplies vocabulary later, check it against what you actually saw.','[Inference] Notice whether you can explain a preference more specifically. Your association may be personal or cultural; it does not establish what every audience feels.')
card(684,'choose-from-an-ai-generated-creative-pool','Choose from an AI-generated creative pool','You have a direction for a creative project and want possible components to consider.','Name the type of material needed; Hische’s example is a list of emotions for a children’s book.|Ask AI for a pool of candidates.|Select the candidates that fit your intended work and discard the rest.|Do the creative development and production you want to retain yourself. Hische explicitly values this work rather than treating it as waste.','[Inference] State why each chosen element belongs. Fast generation and retained enjoyment do not establish improved independent creativity.')
review(741,'Melanie Perkins, interviewed by Lenny Rachitsky','retain','00:53:57–00:55:20; L407–429','First-person routine','Reports dictating her thoughts during walks, then summarizing them to identify actions and gain perspective.','Articulate concerns before organizing them with AI.','The adjacent AI-first ideation habit is a different sequence and not evidence for thinking first.|A summary can omit a concern or turn speculation into a commitment.|Walking is optional; access and privacy conditions vary.','Retain dictation-then-summary sequence; do not label it a live AI conversation or a measured creativity intervention.')
card(741,'speak-your-thoughts-before-summarizing','Speak your thoughts before summarizing them with AI','Messages and tasks crowd your attention and you need to hear your own priorities.','Record or dictate what is on your mind; Perkins does this during a walk.|Ask AI to summarize the resulting notes.|Use the summary to identify possible actions and a broader view.|[Inference] Compare against your original notes and choose the actions yourself; correct omitted concerns or invented commitments. A seated voice note or written note is an alternative to walking.','[Inference] Notice whether the action list reflects your priorities rather than merely the easiest items to summarize.')

review(750,'Mike Krieger, interviewed by Lenny Rachitsky','retain','00:09:00–00:11:14; L116–129','First-person family routine','Describes replacing an immediate request to Claude with a question about how to find out; no learning assessment.','Keep the child involved in choosing an inquiry route.','Confidence in a child’s answer is not accuracy; the coral anecdote demonstrates stance, not verification.|The guest leads an AI product organization.|No age-specific outcome or general developmental benefit established.','Retain the question-before-tool sequence and merge two human inquiry variants without claiming the same evidence basis.')
card(750,'ask-how-to-find-out-before-asking-ai','Ask how to find out before asking AI','A child asks a factual question and reaching for AI would end the inquiry immediately.','Ask the child how you could find out before opening AI.|Consider a feasible observation, simple experiment, book or person to ask.|Pursue an appropriate route together. Joel Salinas (474) describes consulting a household encyclopedia first and using supervised AI for further questions.|If AI is useful afterward, compare its answer with what you found. [Inference] Keep unresolved disagreement visible rather than treating either the child’s confidence or AI’s fluency as proof.|Kunal Shah’s proposed variant (714) asks a why question at a meal and returns to the child’s inquiry the next day.','[Inference] Notice whether the child can explain a way to investigate another question. An enjoyable exchange is not evidence of lasting learning.')
review(474,'Sam Illingworth and named parent contributors, especially Joel Salinas','merge','L61–241, all community reflections|L165–171, Joel Salinas|L209–225, Jenny Ouyang','Collection of first-person parent accounts','Salinas describes encyclopedia-first inquiry. Ouyang describes adult-supplied image guidance and math questions followed by child drawing and paper work. Accounts differ in age and rules.','Support family inquiry and real-world activity with adult judgment.','Parent anecdotes are not developmental comparisons.|Sweeping research and screen-time claims in the introduction are not adopted.|Supervision and an achieved artifact do not by themselves demonstrate retained skill.','Merge the encyclopedia variant into inquiry-first. Keep Ouyang’s child-does-the-work example in the source distillation as an adjacent example, without endorsing her agent setup.',750)
review(714,'Kunal Shah, interviewed by Lenny Rachitsky','merge','00:59:49–01:02:17; L1742–1812','Proposed family inquiry exercise','No child outcomes reported for the Whyfi school exercise.','Encourage investigating a why question and returning with an answer.','Claim that second-order thinking develops automatically is unsupported in this account.|Historical origins may have multiple causes or uncertain evidence.|No AI component is described by the speaker.','Merge as a non-AI inquiry variant, clearly a proposal rather than family-use evidence.',750)
review(412,'Sam Illingworth','retain','L15–19, family encounter|L117–127, five alternatives|L135–143, uncertainty','Parent anecdote and proposed education-policy practices','Reports a child repeating an anti-AI position learned from other children; does not report outcomes of the five proposed practices.','Hear children’s existing use and concerns before setting or revising rules.','The article’s legal and policy claims were not independently refreshed in this review.|Listening does not replace adult responsibilities or tool assessment.|The article itself recognizes uncertainty; comparisons with other prohibition policies are analogies, not causal AI evidence.','Extract the conversation routine only. Do not adopt a blanket verdict for or against school bans.')
card(412,'ask-children-about-ai-before-setting-rules','Ask children about AI before setting rules','You are making a family or classroom AI rule without knowing what children already use or believe.','Ask what they think AI is for, what they use and what worries them; write down their responses.|Ask whom they could consult if AI tells them something important.|Discuss when a system might be guessing and who benefits from a convincing answer.|[Inference] Use what you heard to explain the rule and its reasons, including questions that remain open. Revisit the conversation as use changes.','[Inference] Notice whether the discussion reveals an assumption you had wrong. This is participation in rule-making, not evidence that every use should be allowed.')

review(550,'Annie Duke, interviewed by Lenny Rachitsky','retain','00:24:54–00:44:06; L204–277|01:05:06–01:10:55; L408–435','Professional facilitation experience and sales-team example','Reports organizations adopting independent-input routines; describes warning signals paired with actions for a sales team. No controlled effect estimate.','Expose differences before discussion; precommit to action when failure signals appear.','Feeling heard and reaching consensus are different; disagreement can remain.|A facilitator still has power over framing and synthesis.|The sales kill criteria are contextual examples, not rules for every project.','Retain independent input; merge advance stopping actions into Doshi’s premortem card as a distinct contribution, not independent validation.')
card(550,'collect-independent-views-before-discussion','Collect independent views before discussion','A meeting risks turning the first confident opinion into the group’s apparent view.','Before the meeting, ask each person separately for ideas, rankings or estimates with a short rationale. Hide other responses until everyone has submitted.|Share the collected views for preparation.|Use the meeting to understand differences. Reflect people’s reasoning back so they can correct your interpretation.|Use the agreed decision authority or private voting process; do not require everyone to claim agreement.|[Inference] Keep shared AI recommendations out of the independent-input phase. If AI later summarizes, check that minority positions remain represented.','[Inference] Notice whether the record includes genuinely different estimates and reasons, and whether the final decision is distinguished from everyone’s personal view.')
review(255,'Melchior Tamisier-Fayard, Theodoros Evgeniou and Anne-Laure Fayard','retain','[p.3] question-based programs|[p.4] AI-free work and expertise|[p.5] Process in parallel|[p.5–6] interfaces','Management synthesis drawing on studies, interviews and reported organizational experiments','Reports a With Company branding comparison: human-led and heavily AI-supported teams worked in parallel, with the human-led proposal selected. No randomized comparison or retained-skill test.','Preserve alternative framings and make human/AI contributions visible.','The experiment compared two team workflows, not a pure AI system against humans.|Reported counts of images and programs are not evidence of lasting reasoning gains.|Underlying studies and programs need their own review before using their claims as primary evidence.','Retain the described parallel creative routes; the rest informs context, not a validated intervention package.')
card(255,'develop-parallel-creative-routes','Develop parallel creative routes before combining them','A team wants to compare what human-led and AI-supported workflows contribute to the same challenge.','Give two groups the same brief and relevant context.|Let one develop a human-led route and the other a heavily AI-supported route separately, following the reported consultancy example.|Bring the resulting routes together and compare their coherence, narrative and contextual fit, as well as the breadth of generated possibilities.|Choose or combine elements using the team’s judgment. [Inference] Preserve the initial routes and reasons for selection so differences remain inspectable.','[Inference] Notice which workflow contributed a useful framing and who can explain it. More images is different from a better proposal or preserved capability.')
review(79,'Ethan Mollick','retain','L37–59, Crowd and Lab|L59–71, testing and benchmarks|L73–79, learning loop','Organizational synthesis with named author demonstration','Reports testing an agent against a business simulation and finding both strengths and errors; organization-wide effects of the full framework are not evaluated here.','Share discoveries, test actual work and adapt workflows with accountable domain expertise.','Adoption and time saved do not establish improved human capability.|Vibe benchmarks can be biased and should not settle consequential reliability.|Broad privacy/compliance assertions and urgency framing are excluded.','Retain the employee-discovery, expert-test, feedback sequence; separate the source’s growth aims from this KB’s capability questions.')
card(79,'test-and-share-a-team-ai-workflow','Test and share a team AI workflow','Useful AI experiments remain private, or a team is copying prompts without understanding where they fail.','Invite people doing the work to bring a useful task-specific workflow and its limitations.|Have a small cross-functional group with domain expertise try it on actual representative tasks.|Compare against the organization’s own standards, inspect errors and revise the workflow.|Share the working version and collect results from use; keep iterating rather than treating the first demonstration as deployment proof.|[Inference] Alongside output quality and total effort, inspect which reasoning people still perform and can explain without the tool.','[Inference] Notice whether coworkers can identify failure conditions and adapt the workflow, not only reproduce its best demonstration.')
review(277,'Ruben Hassid','merge','L74–230, setup and sample|L236–298, templates and comparison|L304–425, colleague trial and feedback','Prescriptive rollout playbook demonstrated with a fictional law firm','Provides a fictional setup and suggested before/after exercise, not measured whole-team adoption or competence gains.','Make a recurring workflow accessible and gather colleague feedback.','A selected wow result encourages confirmation bias; tone and format do not establish legal or factual correctness.|Workspace-wide sharing may violate existing access boundaries.|Claims that a team plan makes every upload safe are not adopted.','Merge reusable examples and colleague feedback into Mollick’s loop. Flag impressive-demo-only evaluation as a failure case, not evidence of learning.',79)
review(542,'Alisa Cohn, interviewed by Lenny Rachitsky','retain','00:49:19–00:55:56; L455–498','Executive-coaching practice explanation','Reports inconsistent understandings in meetings she observes; no quantified comparison.','Make decisions, owners, timing and communication obligations explicit.','A visible summary can silence disagreement if it appears settled too early.|AI adaptation is inferred, not evaluated in the interview.|Being listed as owner does not establish actual agreement or authority.','Retain independent accounts of what was decided before reconciling the final record.')
card(542,'check-what-each-person-thinks-was-decided','Check what each person thinks was decided','A meeting is ending and a tidy summary may conceal different understandings.','Reserve time at the end. Ask participants what they think was decided; Cohn describes having people write their answers.|Compare the accounts and surface differences before declaring agreement.|Record what was decided, who does what by when, and who else needs to know.|Assign responsibility for follow-up and make correction part of the ritual.|[Inference] If AI produced meeting notes, compare them with the reconciled human record rather than letting them define the decision.','[Inference] Notice whether unresolved items stay unresolved in the record. Apparent agreement with a displayed summary may hide dissent.')
review(804,'Shreyas Doshi, interviewed by Lenny Rachitsky','retain','00:23:58–00:33:54; L176–222','Repeated professional facilitation account and detailed procedure','Reports surfacing overlooked risks and teams later reusing a shared vocabulary; avoided failures remain counterfactual.','Expose threats early and convert concerns into mitigation or stopping actions.','Benefits are practitioner reports, not a controlled comparison.|A vote for a frightening threat does not estimate its probability.|An action plan and follow-through matter; a list of risks alone is insufficient.','Retain the private-input and action-plan routine; credit the source’s attribution to Gary Klein for the premortem idea and Duke for explicit signal/action commitments.')
card(804,'turn-a-premortem-into-actions','Turn a premortem into actions and stopping criteria','An important launch has risks people hesitate to raise.','Bring relevant functions together and imagine the project has failed at a future date.|Give participants quiet time to record real threats, apparent threats they consider less serious, and unspoken concerns. Keep entries hidden initially.|Share concerns. Ask each participant to identify a serious threat raised by someone else.|The leader prioritizes and publishes an action plan, then remains accountable for follow-through.|Annie Duke’s variant (550): specify observable failure signals in advance and pair each with an action, further inquiry, pivot or stop.|[Inference] If AI adds scenarios, do so after independent human input and keep generated possibilities separate from observed warning signals.','[Inference] Notice whether a concern changed an action or stopping rule. A longer risk list is not a safer project.')
review(811,'Tanguy Crusson, interviewed by Lenny Rachitsky','retain','00:28:22–00:31:32; L258–283','First-person product-team routine','Reports returning to recent user interviews together when competitor AI announcements distract the team.','Reground priorities in real users and the problem being served.','Recent interviews can be unrepresentative.|Ignoring competitors entirely is not the account’s prescription; it includes periodic review.|No measured effect on judgment or product outcomes.','Retain a specific team grounding routine, not the sweeping claim that competitors should be ignored.')
card(811,'return-to-real-user-accounts','Return to real user accounts when AI ideas distract','A new AI launch or competitor feature is pulling the team away from the people it serves.','Revisit recent user interviews together rather than reacting only to announcements.|Discuss who the team is building for and which problem those people actually describe.|Compare the exciting possibility with that problem and the team’s longer-term direction.|[Inference] Preserve conflicting user accounts and decide whether additional inquiry is needed before changing priorities.','[Inference] Notice whether the proposal answers a user need or merely copies a visible feature. Interviews support judgment; they do not automatically validate demand.')

research={
10:('guingrich-belief-offloading-2026','Guingrich, Mehta and Bhatt offer a conceptual account of [[belief-offloading]], not evidence that this routine prevents it.'),
11:('doshi-hauser-creativity-diversity-2024','Doshi and Hauser’s short-story experiment separates ratings of individual outputs from diversity across outputs. It does not evaluate this practice or establish lasting creative skill.'),
12:('bastani-guardrails-math-rct-2025','Bastani and colleagues distinguish assisted practice from later unaided mathematics performance. That school study does not evaluate these family conversations or justify an age-general rule.'),
13:('anderson-homogenization-2024','Anderson and colleagues found group-level similarity in a small creative-ideation comparison. It does not test this team routine or establish retained expertise.')}

assert set(reviews)=={s['id'] for s in manifest['sources'] if 10<=s['group_index']<=13}
for id,r in reviews.items():
    s=sources[id]; wb=ROOT/s['workbench']; text=(wb/'source.md').read_text(encoding='utf-8'); lines=len(text.splitlines())
    transcript=s['collection']=="Lenny's Podcast"
    r['coverage']=(f'Close-read complete relevant transcript exchanges at listed timestamps and surrounding context; not full {lines}-line transcript; audio/video not reviewed.' if transcript else f'Close-read all {lines} lines of available extracted article text; image-only content and linked media not reviewed.')
    if id==255:r['coverage']='Close-read all six available extracted PDF pages, lines 1–207. Page images not rendered; linked underlying studies not reread.'
    if id==270:r['coverage']+=' Available article stops at section 3 heading; not a full original article.'
    r['related_entries']=['agency',research[r['group_index']][0]]
    r['practice_files']=[str(Path(sources[c['id']]['workbench'])/'drafts/practices'/f"{c['stem']}.md").replace('\\','/') for c in cards if c['id']==id or c['id']==r['merge'] or (id==550 and c['id']==804)]
    r['role']='origin' if r['decision']=='retain' else {'merge':'support','counterexample':'counterexample','defer':'deferred'}[r['decision']]
    r['draft_only']=True; r['integration_decision']='pending'
    citation=f"{r['author']}. ({s['date']}). {s['title']}. {s['url']}"
    related='\n'.join(f'- [[{e}]]' for e in r['related_entries'])
    findings='\n'.join(f'- {x}' for x in [r['review_note'],r['reported_outcomes'][0]])
    locations='; '.join(r['locators'])
    limits='\n'.join(f'- {x}' for x in r['limits'])
    files='\n'.join('- '+p for p in r['practice_files']) or '- No standalone practice draft.'
    (wb/'drafts').mkdir(exist_ok=True)
    (wb/'practice-review.json').write_text(json.dumps({k:v for k,v in r.items() if k!='merge'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (wb/'triage.md').write_text(f"# Triage: {s['title']}\n\n## Source and Coverage\n\n{citation}\n\n{r['coverage']}\n\n## Summary\n\n{r['review_note']}\n\n**Basis:** {r['basis']}.\n\n## Relevance and Quality\n\nHigh relevance to examining AI-supported thinking. Practitioner evidence retained with limits; no general author trust score. {r['proposed_outcomes'][0]}\n\n{r['reported_outcomes'][0]}\n\n## Duplication / Related Entries\n\n{related}\n\n{('Contribution merged into source '+str(r['merge'])+'.') if r['merge'] else 'No canonical duplicate claimed; concrete workflow complements existing concepts.'}\n\n## Recommendation\n\n{r['decision'].upper()} — {r['review_note']}\n\n## Decision\n\n- Outcome: draft-only {r['decision']}\n- Date: 2026-09-26\n- Reason: User authorized continued review and draft preparation; integration pending.\n",encoding='utf-8')
    (wb/'drafts/source.md').write_text(f"---\nstatus: emerging\narea: [preservation]\ntype: {'transcript' if transcript else 'article'}\nsources:\n  - {json.dumps(citation,ensure_ascii=False)}\n---\n\n# {s['title']}\n\n## Citation\n\n{citation}\n\n## Key Insight\n\n{r['review_note']}\n\n## Key Findings\n\n{findings}\n\n**Locators:** {locations}. Findings paraphrased from the archived source, not quotations.\n\n## Evidence\n\n**Basis:** {r['basis']}.\n\n**Reported:** {r['reported_outcomes'][0]}\n\n**Proposed:** {r['proposed_outcomes'][0]}\n\n**Coverage:** {r['coverage']}\n\n## Limits\n\n{limits}\n\n## Supports / Relates To\n\n{related}\n\n{research[r['group_index']][1]}\n\n## Draft Disposition\n\n{files}\n\nDraft-only. Canonical source integration and practice decisions pending.\n",encoding='utf-8')
    (wb/'distill.md').write_text(f"# Distillation: {s['title']}\n\n## Extraction Ledger\n\n- Concepts: none; no new construct inferred from a practitioner account.\n- Methods: none; practice drafts remain separate.\n- Practices: {r['decision']}. {r['review_note']}\n- Source: drafts/source.md\n\n## Locators\n\n{locations}\n\n## Reported Versus Proposed\n\nReported: {r['reported_outcomes'][0]}\n\nProposed: {r['proposed_outcomes'][0]}\n\n## Files / Consolidation\n\n{files}\n\n## Decision\n\n- Outcome: PROCEED_TO_CRITIQUE for draft preparation only\n- Date: 2026-09-26\n- Integration: pending\n",encoding='utf-8')
    concern=' '.join(r['limits'])
    (wb/'critique.md').write_text(f"# Self-Critique: {s['title']}\n\n## Overall: FLAGS\n\n## Evidence Lens — APPROVE bounded draft\n\n{r['reported_outcomes'][0]} Claims in the draft remain at this level. Intended outcome: {r['proposed_outcomes'][0]} No causal benefit or independent skill gain is inferred.\n\n## Practitioner Lens — APPROVE draft scope\n\n{r['review_note']} Concrete instructions are retained where available; proposed adaptations are labelled [Inference]. {('No standalone card is offered.' if r['decision'] in ['defer','counterexample'] else 'Use conditions and human choices are explicit in the associated card.')}\n\n## Adversarial Lens — FLAGS\n\n{concern}\n\n## AI Failure Checklist\n\n- Citations: attribution and original locator retained; no invented research citation.\n- Methodology: practitioner account or proposal kept separate from evaluation.\n- Statistics: no numerical benefit claimed; source timeboxes are suggestions.\n- Constructs: output, felt clarity, choice, and unaided capability not equated.\n- Status: emerging; draft-only.\n- Links: related entries checked locally; practice references use draft paths.\n- Novelty: overlaps consolidated; no new concept minted.\n\n## Decision\n\n- Outcome: pending integration review\n- Date: 2026-09-26\n- Reason: Draft critique complete with stated evidence limits; no canonical write authorized by this artifact.\n",encoding='utf-8')
    meta=json.loads((wb/'source.json').read_text(encoding='utf-8')); meta.update(status='critiqued',draft_only=True,integration_decision='pending')
    meta['decisions']=[d for d in meta.get('decisions',[]) if d.get('stage')!='practice-review']
    meta['decisions'].append(dict(stage='practice-review',outcome=r['decision'],date='2026-09-26',reason=r['review_note'],integration='pending'))
    if id==255:
        meta['bibliographic_metadata'].update(date=s['date'],url=s['url'],author=r['author'],verification_note='Prior verified screening record: raw/practitioner-practices-development/screening/shortlist.md, PDF bibliography note. Local PDF has no byline.')
    (wb/'source.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    if 'Close review, distillation and three-lens critique completed' not in (wb/'log.md').read_text(encoding='utf-8'):
        with (wb/'log.md').open('a',encoding='utf-8') as f:f.write(f"\n- 2026-09-26 — Close review, distillation and three-lens critique completed. Disposition: {r['decision']}. Draft-only; integration pending. Coverage: {r['coverage']}\n")

for c in cards:
    id=c['id'];s=sources[id];r=reviews[id];wb=ROOT/s['workbench'];p=wb/'drafts/practices';p.mkdir(exist_ok=True)
    citation=f"{r['author']}. ({s['date']}). {s['title']}. {s['url']}"
    supporting=[(i,x) for i,x in reviews.items() if x['merge']==id or (id==804 and i==550)]
    support='\n'.join(f"- {x['author']}, [{sources[i]['title']}]({sources[i]['url']}), {sources[i]['date']}; {'; '.join(x['locators'])}. {x['reported_outcomes'][0]}" for i,x in supporting)
    limits='\n'.join('- '+x for x in r['limits'])
    steps='\n'.join(f'{n}. {step}' for n,step in enumerate(c['steps'],1))
    rel=research[r['group_index']]
    doc=f"---\nstatus: emerging\narea: [preservation]\nsources:\n  - {json.dumps(citation,ensure_ascii=False)}\n---\n\n# {c['title']}\n\n## Use When\n\n{c['use']}\n\nAuthor’s intended benefit: {r['proposed_outcomes'][0]}\n\n## Try It\n\n{steps}\n\n## Origin\n\n{citation}\n\nLocators: {'; '.join(r['locators'])}. Practice title is an editorial label.\n\n{support}\n\n## Evidence and Rationale\n\n**Basis:** {r['basis']}.\n\n**Observed or reported:** {r['reported_outcomes'][0]}\n\n**Related research:** {rel[1]} See [[{rel[0]}]]. This is context, not direct validation.\n\n**Untested:** Whether this specific procedure improves judgment, independent capability, creative quality or calibration beyond the reported experience. A completed artifact, more options and felt clarity are different outcomes.\n\n## Limits\n\n{limits}\n\n## What to Notice\n\n{c['notice']}\n\n## Related\n\n- [[agency]] — keeping a final choice does not alone establish informed or independent judgment.\n- [[{rel[0]}]] — bounded research context described above.\n\n## Draft Status\n\nCritiqued draft only. Integration decision pending.\n"
    variants={512:"### Distinct variants\n\n- Ramonov (387): supply relevant business context, then request three to five overlooked questions, counterarguments or risks about an idea. The user still needs to answer and verify them. [Inference] Do not equate a harsh critique with accuracy.\n- Gorb (515): give three to five current ideas and background points; ask one question at a time about what starting would require you to give up, with no advice or conclusions. Define vague success expectations concretely. [Inference] Reject questions that presume hidden motives or equate discomfort with the right choice.\n- Hassid (270): ask for opposing simulated perspectives after checking an unsupported business-plan assumption. [Inference] Treat the perspectives as generated possibilities; check any evidence they cite.\n\n",524:"### Earlier-era constraint variant\n\nO’Hanley (530) proposes asking for current, 1990 and 1970 perspectives, each limited to 150 words and containing one insight, one blind spot and one possible decision. Choose one useful simplification and test it for 30 minutes. [Inference] These are imagined constraints unless checked against period sources; the prompt cannot guarantee historically bounded knowledge.\n\n"}
    if id in variants:doc=doc.replace('## Origin\n',variants[id]+'## Origin\n')
    (p/f"{c['stem']}.md").write_text(doc,encoding='utf-8')

print(json.dumps({'reviews':len(reviews),'cards':len(cards),'dispositions':{k:sum(r['decision']==k for r in reviews.values()) for k in ['retain','merge','defer','counterexample']}},indent=2))
